# ROCKCHIP Platform Support
snd-soc-i2s-objs := rockchip_i2s.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_I2S) += snd-soc-i2s.o

# ROCKCHIP Machine Support
snd-soc-rockchip-max98090-objs := rockchip_max98090.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_MAX98090) += snd-soc-rockchip-max98090.o

snd-soc-wm8960-objs := rockchip_wm8960.o
snd-soc-rt5631-objs := rockchip_rt5631.o
obj-$(CONFIG_SND_SOC_ROCKCHIP_WM8960) += snd-soc-wm8960.o
obj-$(CONFIG_SND_RK_SOC_RT5631) += snd-soc-rt5631.o

